version: '3.8'
services:
  api:
    container_name: cm-api
    image: countmoneycontainerregistry.azurecr.io/cm-api:latest
    #image: cm-api
    restart: always
    build: ./api
    ports:
      - "443:8080"
    depends_on:
      - cache_node

  web:
    container_name: cm-web
    image: countmoneycontainerregistry.azurecr.io/cm-web:latest
    #image: cm-web
    build: ./web
    ports:
      - "80:3000"
    depends_on:
      - api

  redis:
    container_name: cm-redis
    image: countmoneycontainerregistry.azurecr.io/cm-redis:latest
    #image: redislabs/redismod
    ports:
      - "6379:6379"
    entrypoint:
      - /bin/bash
      - -c
      - redis-server
          --loadmodule /usr/lib/redis/modules/rejson.so


  cache_node:
    container_name: cm-cache
    image: countmoneycontainerregistry.azurecr.io/cm-cache:latest
    #image: cm-cache
    build: ./cacheMicroservice
    ports:
      - "8081:8081"
    depends_on:
      - redis

  websocket_server:
    container_name: cm-websocket
    image: countmoneycontainerregistry.azurecr.io/cm-websocket:latest
    #image: cm-websocket
    build: ./websocketServer
    ports:
      - "8082:8082"
    depends_on:
      - redis
    
    
    
