version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  producer:
    build: ./Scrapper
    volumes:
      - ./Scrapper:/usr/src/app
    depends_on:
      rabbitmq:
        condition: service_healthy

  consummer:
    build: ./Consummers/tendencies
    volumes:
      - ./Consummers/tendencies:/usr/src/app
    depends_on:
      rabbitmq:
          condition: service_healthy

