FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the entire project and install dependencies
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run the FastAPI app using Uvicorn
CMD ["uvicorn", "global_api.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
